name: Daily AIESEC Scraper

on:
  schedule:
    - cron: '37 3 * * *'  # Runs every day at 5:30 AM 
  workflow_dispatch:      # Allows manual trigger in GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          ref: Sakr

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 pandas openpyxl lxml

      - name: Run scraper
        run: python aiesec.py
      - name: Commit and push updated Excel files with datetime message
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.xlsx
          if git diff --cached --quiet; then
            echo "No changes in Excel files to commit."
          else
            COMMIT_MSG="Update Excel files after daily scrape - $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            git commit -m "$COMMIT_MSG"
            git push origin Sakr
          fi
