name: Daily AIESEC Scraper

on:
  schedule:
    - cron: '20 1 * * *'  # Runs every day at 5:00 AM UTC
  workflow_dispatch:      # Allows manual trigger in GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          sudo ln -s /usr/bin/chromedriver /usr/local/bin/chromedriver

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium beautifulsoup4 pandas openpyxl lxml

      - name: Run scraper
        run: python aiesec.py
